# -*- coding: utf-8 -*-
"""Weather Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SELnDR0bJuNgIGulg_vv39eMgHrQ-V6x

Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset"""

df = pd.read_csv("/content/climate_data.csv")

"""Display First 5 Rows"""

print(df.head())

"""Dataset Information"""

print(df.info())

"""Check Missing Values"""

print("\nMissing Values:")
print(df.isnull().sum())

"""Fill Missing Values with Mean"""

df.fillna(df.mean(numeric_only=True), inplace=True)

"""Convert Date Column to Datetime"""

df['Date'] = pd.to_datetime(df['Date'])

"""Basic Statistics"""

print("\nDescriptive Statistics:")
print(df.describe())

"""Create Season Column"""

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Summer'
    elif month in [6, 7, 8]:
        return 'Monsoon'
    else:
        return 'Autumn'

df['Season'] = df['Date'].dt.month.apply(get_season)

"""Visualization

Line Plot – Temperature Trend
"""

plt.figure(figsize=(12,5))
plt.plot(df['Date'], df['Average temperature (°F)'], marker='o')

plt.title("Average Temperature Trend")
plt.xlabel("Date")
plt.ylabel("Temperature (°F)")
plt.xticks(rotation=45)

plt.show()

"""Bar Chart – Seasonal Rainfall"""

seasonal_rainfall = df.groupby('Season')['Rainfall for month (in)'].mean()

plt.figure(figsize=(8,5))
seasonal_rainfall.plot(kind='bar')

plt.title("Average Seasonal Rainfall")
plt.xlabel("Season")
plt.ylabel("Rainfall (inches)")

plt.show()

"""Histogram – Temperature Distribution"""

plt.figure(figsize=(8,5))

plt.hist(
    df['Average temperature (°F)'],
    bins=20
)

plt.title("Temperature Distribution")
plt.xlabel("Temperature (°F)")
plt.ylabel("Frequency")

plt.show()

"""Scatter Plot – Temperature vs Humidity"""

plt.figure(figsize=(8,5))

plt.scatter(
    df['Average temperature (°F)'],
    df['Average humidity (%)']
)

plt.title("Temperature vs Humidity")
plt.xlabel("Temperature (°F)")
plt.ylabel("Humidity (%)")

plt.show()

"""Pie Chart – Seasonal Distribution"""

season_count = df['Season'].value_counts()

plt.figure(figsize=(7,7))

plt.pie(
    season_count,
    labels=season_count.index,
    autopct='%1.1f%%'
)

plt.title("Seasonal Distribution")

plt.show()

"""Heatmap – Correlation Analysis"""

import seaborn as sns

numeric_df = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(10,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()